# Generated by Django 4.2.7 on 2023-11-29 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='image',
        ),
    ]
