# Generated by Django 4.2.7 on 2023-11-29 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_remove_photo_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='image',
            field=models.ImageField(default='ska foto', upload_to='photos/'),
        ),
    ]
