# Generated by Django 4.2.7 on 2023-12-17 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_userlogin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserLogIn',
        ),
    ]
