# Generated by Django 4.2.7 on 2023-12-19 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_delete_userlogin'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='owner_id',
            field=models.IntegerField(null=True),
        ),
    ]
