# Generated by Django 4.2.7 on 2024-02-02 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='owner_id',
        ),
        migrations.AddField(
            model_name='account',
            name='birthday',
            field=models.DateField(default='2000-01-01'),
        ),
    ]
